server:
  port: 80
  
spring:
  cloud:
    config:
      uri: localhost:8888
      profile: jdbc
      label: master
  application:
    name: springcloud-config-client
eureka:
 client:
   register-with-eureka: false
   service-url:
     defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/